version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:delegated
      - ./storage:/var/www/html/storage:delegated
      - ./vendor:/var/www/html/vendor:delegated
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_DATABASE: mental_health_db
      DB_USERNAME: general_user
      DB_PASSWORD: general@2024  # Ensure this matches your MySQL setup.
      MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: false
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mental_health_db
      MYSQL_USER: general_user
      MYSQL_PASSWORD: general@2024  # Ensure this matches your app service.
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3307:3306"
    
volumes:
  dbdata:
  
networks:
  laravel_net: