version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:delegated
      - ./storage:/var/www/html/storage:delegated
      - ./vendor:/var/www/html/vendor:delegated
    environment:
      APP_ENV: local
      DB_HOST: db
      DB_DATABASE: mental_health_db
      DB_USERNAME: general_user
      DB_PASSWORD: general@2024
      MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: "false"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mental_health_db
      MYSQL_USER: general_user
      MYSQL_PASSWORD: general@2024
      MYSQL_ROOT_PASSWORD: 'Crewso@26'  # Add this line
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "general_user", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:

networks:
  default:
    name: laravel_net